using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class EffectResolve : MonoBehaviour
{
    public GameObject WaterStraight;
    public GameObject WaterSphere;
    public GameObject WaterSpread;
    public GameObject WaterRay;
    public GameObject WaterWave;
    public GameObject WaterGatling;
    public GameObject WaterRayEffect;
    public GameObject WaterGatlingEffect;
    public GameObject WaterStraightHit;
    public GameObject WaterSphereHit;
    public GameObject WaterSpreadHit;
    public GameObject WaterRayHit;
    public GameObject WaterWaveHit;
    public GameObject WaterGatlingHit;

    public GameObject LifeStraight;
    public GameObject LifeSphere;
    public GameObject LifeSpread;
    public GameObject LifeRay;
    public GameObject LifeWave;
    public GameObject LifeGatling;
    public GameObject LifeRayEffect;
    public GameObject LifeGatlingEffect;
    public GameObject LifeStraightHit;
    public GameObject LifeSphereHit;
    public GameObject LifeSpreadHit;
    public GameObject LifeRayHit;
    public GameObject LifeWaveHit;
    public GameObject LifeGatlingHit;

    public GameObject LightStraight;
    public GameObject LightSphere;
    public GameObject LightSpread;
    public GameObject LightRay;
    public GameObject LightWave;
    public GameObject LightGatling;
    public GameObject LightRayEffect;
    public GameObject LightGatlingEffect;
    public GameObject LightStraightHit;
    public GameObject LightSphereHit;
    public GameObject LightSpreadHit;
    public GameObject LightRayHit;
    public GameObject LightWaveHit;
    public GameObject LightGatlingHit;

    public GameObject LightningStraight;
    public GameObject LightningSphere;
    public GameObject LightningSpread;
    public GameObject LightningRay;
    public GameObject LightningWave;
    public GameObject LightningGatling;
    public GameObject LightningRayEffect;
    public GameObject LightningGatlingEffect;
    public GameObject LightningStraightHit;
    public GameObject LightningSphereHit;
    public GameObject LightningSpreadHit;
    public GameObject LightningRayHit;
    public GameObject LightningWaveHit;
    public GameObject LightningGatlingHit;

    public GameObject DarknessStraight;
    public GameObject DarknessSphere;
    public GameObject DarknessSpread;
    public GameObject DarknessRay;
    public GameObject DarknessWave;
    public GameObject DarknessGatling;
    public GameObject DarknessRayEffect;
    public GameObject DarknessGatlingEffect;
    public GameObject DarknessStraightHit;
    public GameObject DarknessSphereHit;
    public GameObject DarknessSpreadHit;
    public GameObject DarknessRayHit;
    public GameObject DarknessWaveHit;
    public GameObject DarknessGatlingHit;

    public GameObject MetalStraight;
    public GameObject MetalSphere;
    public GameObject MetalSpread;
    public GameObject MetalRay;
    public GameObject MetalWave;
    public GameObject MetalGatling;
    public GameObject MetalRayEffect;
    public GameObject MetalGatlingEffect;
    public GameObject MetalStraightHit;
    public GameObject MetalSphereHit;
    public GameObject MetalSpreadHit;
    public GameObject MetalRayHit;
    public GameObject MetalWaveHit;
    public GameObject MetalGatlingHit;

    public GameObject FireStraight;
    public GameObject FireSphere;
    public GameObject FireSpread;
    public GameObject FireRay;
    public GameObject FireWave;
    public GameObject FireGatling;
    public GameObject FireRayEffect;
    public GameObject FireGatlingEffect;
    public GameObject FireStraightHit;
    public GameObject FireSphereHit;
    public GameObject FireSpreadHit;
    public GameObject FireRayHit;
    public GameObject FireWaveHit;
    public GameObject FireGatlingHit;

    public GameObject IceStraight;
    public GameObject IceSphere;
    public GameObject IceSpread;
    public GameObject IceRay;
    public GameObject IceWave;
    public GameObject IceGatling;
    public GameObject IceRayEffect;
    public GameObject IceGatlingEffect;
    public GameObject IceStraightHit;
    public GameObject IceSphereHit;
    public GameObject IceSpreadHit;
    public GameObject IceRayHit;
    public GameObject IceWaveHit;
    public GameObject IceGatlingHit;

    public GameObject WindStraight;
    public GameObject WindSphere;
    public GameObject WindSpread;
    public GameObject WindRay;
    public GameObject WindWave;
    public GameObject WindGatling;
    public GameObject WindRayEffect;
    public GameObject WindGatlingEffect;
    public GameObject WindStraightHit;
    public GameObject WindSphereHit;
    public GameObject WindSpreadHit;
    public GameObject WindRayHit;
    public GameObject WindWaveHit;
    public GameObject WindGatlingHit;

    public GameObject MountainStraight;
    public GameObject MountainSphere;
    public GameObject MountainSpread;
    public GameObject MountainRay;
    public GameObject MountainWave;
    public GameObject MountainGatling;
    public GameObject MountainRayEffect;
    public GameObject MountainGatlingEffect;
    public GameObject MountainStraightHit;
    public GameObject MountainSphereHit;
    public GameObject MountainSpreadHit;
    public GameObject MountainRayHit;
    public GameObject MountainWaveHit;
    public GameObject MountainGatlingHit;

    public GameObject BrokenEffect;
    public GameObject ParalyzedEffect;
    public GameObject BurntEffect;
    public GameObject PoisonedEffect;
    public GameObject FrozenEffect;

}
